CREATE TABLE 图书馆(
	编号 CHAR(6) NOT NULL,
	名称 VARCHAR(50) NOT NULL,
	地址 VARCHAR(100),
	电话 CHAR(11),
	PRIMARY KEY(编号)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE 出版社(
	编号 CHAR(7) NOT NULL,
	名称 VARCHAR(100) NOT NULL,
	国家 VARCHAR(20)  NOT NULL DEFAULT'中国',
	城市 VARCHAR(20),
	地址 VARCHAR(100),
	邮编 CHAR(10),
	网址 VARCHAR(50),
	PRIMARY KEY(编号)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE 作者(
	编号 CHAR(8) NOT NULL,
	姓名 VARCHAR(20) NOT NULL,
	性别 CHAR(1) CHECK(性别 IN('男','女')),
	出生年代 VARCHAR(20) DEFAULT '当代',
	国籍 VARCHAR(20) DEFAULT '中国',
	PRIMARY KEY(编号)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE 图书(
	ISBN CHAR(10) NOT NULL,
	书名 VARCHAR(100) NOT NULL,
	类型 CHAR(6)  NOT NULL,
	语言 CHAR(6)  DEFAULT '中文',
	价格 INT CHECK(价格>0 AND 价格<5000),
	开本 VARCHAR(10) CHECK(开本 IN('850*1168','184*260','880*1230','140*112')),
	千字数 SMALLINT CHECK(千字数 > 0),
	页数 SMALLINT,
	印数 INT,
	出版日期 DATE NOT NULL,
	印刷日期 DATE,
	出版社号 CHAR(7) NOT NULL REFERENCES 出版社(编号),
	PRIMARY KEY(ISBN)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;


CREATE TABLE 收藏(
	图书馆号 CHAR(6) NOT NULL,
	ISBN CHAR(10) NOT NULL,
	收藏日期 DATE,
	PRIMARY KEY(图书馆号,ISBN),
	FOREIGN KEY(图书馆号) REFERENCES 图书馆(编号),
	FOREIGN KEY(ISBN) REFERENCES 图书(ISBN)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE 编著(
	ISBN CHAR(10) NOT NULL,
	作者号 CHAR(8) NOT NULL,
	类别 CHAR(4) CHECK(类别 IN('主编','主审','编著者','译者')),
	排名 SMALLINT,
	PRIMARY KEY(ISBN,作者号),
	FOREIGN KEY(ISBN) REFERENCES 图书(ISBN),
	FOREIGN KEY(作者号) REFERENCES 作者(编号)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;


CREATE TABLE 客户(
	客户ID CHAR(20) NOT NULL,
	名称 VARCHAR(50) NOT NULL,
	地址 VARCHAR(100),
	电话 CHAR(11),
	PRIMARY KEY(编号)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;

